server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/webserialdb

app:
  mqtt:
    broker: tcp://localhost:1883
    clientId: web-serial-server
    topic: device/+/serial/raw
